### ISSUE TITLE
Where to access running exist container?

### ISSUE THREAD

**Issue by nathangibson** [usaybia/srophe-docker#1]
Hi @wsalesky 

This docker image builds without any errors on my local machine. Yay! But although docker shows it as running and healthy on ports 8080/tcp, 8443/tcp, I can't get to it in my browser at localhost:8080 etc. Does this involve a network setting for docker? Or is it possibly related to this error message in the log: 
```
WARN (Descriptor.java [<init>]:116) - Giving up unable to read descriptor.xml file from classloader in package org.exist.http, eXist-db Core, version 5.2
```
Or perhaps to this line in the docker-compose? https://github.com/usaybia/srophe-docker/blob/master/docker-compose.yml#L10 

related: usaybia/srophe-eXist-app/issues/43

**Comment by wsalesky** [comment]
@nathangibson run  `docker ps -a` to see all running containers, it should give you the urls and ports.

**Comment by nathangibson** [comment]
Oh, duh, I didn't explicitly bind the ports in the run command (thought I didn't need to since they are exposed in the Dockerfile). Thanks!

**Comment by wsalesky** [comment]
No worries,  I'm still learning Docker also and constantly having to look things up or ask questions!
