### ISSUE TITLE
Name and versioning? 

### ISSUE THREAD

**Issue by nathangibson** [usaybia/srophe-docker#2]
@wsalesky Good news! I succeeded in building the docker image and publishing it as a "package": https://github.com/usaybia/srophe-docker/packages

I'm interested in your thoughts: Should I keep the name "usaybia/srophe" for packages? I don't think it creates any confusion with other srophe (non-usaybia) packages, right? 

And should the version numbers be independent of my version numbers for the data and srophe-exist-app releases, which this package incorporates? I'm supposing so.

**Comment by wsalesky** [comment]
@nathangibson I think it is fine to leave it as 'usaybia/srophe' 

In terms of the version numbers it might make sense to just plan a docker release for each major version change of the app, so I would be inclined to sync those, just for major versions, not minor.

**Comment by nathangibson** [comment]
@wsalesky Ya, for archival purposes we wouldn't need more than major release versions. It's just that I'm updating the website pretty frequently now and thinking of incorporating this docker build and pull process as the way I do that. 

But a thought occurred to me--maybe I can use this srophe-docker repo for the settings but actually release the docker images via the usaybia/srophe-exist-app repo, where it logically belongs. And then it would definitely make sense to match the srophe app version numbers.
